---
name: minio
director_uuid: UUID

releases:
- name: minio
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 'latest'

instance_groups:
- name: minio
  azs: [z1]
  instances: 1
  jobs:
  - name: minio-server
    release: minio
    templates:
    - name: minio-server
    properties:
      credential:
        accesskey: minio
        secretkey: minio123
        port: 9000
  networks:
  - name: default
  vm_type: default
  persistent_disk_type: 2048
  stemcell: default

update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 10

