mc:
  size: 8222112
  object_id: 51e1c6aa-eb19-48d8-5008-ad6d6543446c
  sha: sha256:77a1de2409b67c1615cdc5af323201c3dd39c3eb57463c717d0385a5fcd2d9be
minio:
  size: 23920960
  object_id: 6f540507-a793-4baa-41e3-537159741b87
  sha: sha256:be8d41379c7dcad07426425f2d02622c176b1bb2602999118e7c87aff33f9748
